databaseChangeLog:
  - changeSet:
      id: 1
      author: xxx
      changes:
        - createTable:
            tableName: USERS
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: username
                  type: varchar(255)
              - column:
                  name: password
                  type: varchar(255)
